name: cce
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - abseil-cpp=20211102.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - arrow-cpp=11.0.0
  - async-timeout=4.0.2
  - attrs=22.1.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - blas=1.0
  - boost-cpp=1.73.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.05.30
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cryptography=41.0.2
  - dataclasses=0.8
  - datasets=2.12.0
  - diffusers=0.18.2
  - dill=0.3.6
  - filelock=3.9.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2023.4.0
  - gflags=2.2.2
  - giflib=5.2.1
  - glog=0.5.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - grpc-cpp=1.46.1
  - huggingface_hub=0.15.1
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - intel-openmp=2021.4.0
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.1.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.52.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.2.1
  - multidict=6.0.2
  - multiprocess=0.70.14
  - ncurses=6.4
  - networkx=2.8.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=1.1.1u
  - orc=1.7.4
  - packaging=23.0
  - pandas=1.5.3
  - pillow=9.4.0
  - pip=23.2.1
  - pyarrow=11.0.0
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.2
  - python-xxhash=2.0.2
  - pytz=2022.7
  - pyyaml=6.0
  - re2=2022.04.01
  - readline=8.2
  - regex=2022.7.9
  - requests=2.31.0
  - responses=0.13.3
  - sacremoses=0.0.43
  - setuptools=68.0.0
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.41.2
  - sympy=1.11.1
  - tk=8.6.12
  - tokenizers=0.13.2
  - tqdm=4.65.0
  - transformers=4.28.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - urllib3=1.26.16
  - utf8proc=2.6.1
  - wheel=0.38.4
  - xxhash=0.8.0
  - xz=5.4.2
  - yaml=0.2.5
  - yarl=1.8.1
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - accelerate==0.21.0
      - psutil==5.9.5
      - torch==1.11.0
      - torchvision